server:
  port: 8088
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/register?serverTimezone=GMT%2b8
    username: root
    password: "031219"

# Mybatis配置
mybatis:
  # 配置XML映射文件中指定的实体类别名路径
  type-aliases-package: com.example.demo.entity
  # 配置MyBatis的xml配置文件路径
  mapper-locations: classpath:mapping/*.xml
  # 开启驼峰uName自动映射到u_name
  configuration:
    map-underscore-to-camel-case: true

